# Generated by Django 3.0.8 on 2020-08-02 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='City',
        ),
    ]
