# Generated by Django 3.0.8 on 2020-08-02 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theapi', '0003_auto_20200802_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='City',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theapi.City'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theapi.Town'),
        ),
    ]
